apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.key | b64enc | quote }}
  SECRET_MULTI: {{ .Values.secrets.multi | b64enc | quote }}
